"""
Generate a pytest test file from recorded flows for a given package.
"""
from __future__ import annotations
from pathlib import Path

from core.recorder import load_flows


def generate(package: str, output_dir: Path) -> Path:
    flows = load_flows(package)
    if not flows:
        raise ValueError(f"No flows recorded for {package}")

    output_dir.mkdir(parents=True, exist_ok=True)
    safe_pkg = package.replace(".", "_").replace("-", "_")
    out_path = output_dir / f"test_{safe_pkg}.py"
    out_path.write_text(_render(package, flows))
    return out_path


def _render(package: str, flows: dict) -> str:
    lines = [
        '"""',
        f"Auto-generated tests for {package}.",
        "Generated by android-app-trainer — edit with care.",
        '"""',
        "import time",
        "import pytest",
        "from pathlib import Path",
        "from core import adb",
        "from core.recorder import FlowPlayer",
        "",
        "",
        f'PACKAGE = "{package}"',
        'SCREENSHOT_DIR = Path("reports/screenshots")',
        "",
        "",
        "@pytest.fixture(scope='session')",
        "def device():",
        "    devices = adb.list_devices()",
        "    assert devices, 'No ADB device connected'",
        "    return devices[0]['serial']",
        "",
        "",
    ]

    for flow_name, actions in flows.items():
        safe_name = flow_name.replace(" ", "_").replace("-", "_").lower()
        lines += _render_flow(safe_name, flow_name, package, actions)

    return "\n".join(lines)


def _render_flow(safe_name: str, display_name: str, package: str,
                 actions: list[dict]) -> list[str]:
    lines = [
        f"class Test_{safe_name.title().replace('_', '')}:",
        f'    """Flow: {display_name}"""',
        "",
        f"    def test_{safe_name}(self, device: str):",
        f'        """Run the \'{display_name}\' flow and assert expected state."""',
        f"        adb.launch_app(PACKAGE, device)",
        f"        player = FlowPlayer(device, SCREENSHOT_DIR)",
        f"        actions = {_repr_actions(actions)}",
        f"        assert player.play(actions), \\",
        f'            f"Flow \'{display_name}\' failed: {{chr(10).join(player.failures)}}"',
        "",
        "",
    ]
    return lines


def _repr_actions(actions: list[dict]) -> str:
    import json
    pretty = json.dumps(actions, indent=8)
    # indent relative to the assignment
    lines = pretty.splitlines()
    result = lines[0]
    for line in lines[1:]:
        result += "\n        " + line
    return result
